### ISSUE TITLE
 this.position is not a function

### ISSUE THREAD

**Issue by YUEchn** [iVis-at-Bilkent/cytoscape.js-undo-redo#24]
When I use it in react, it throw out error, 
**cytoscape-undo-redo.js:234 Uncaught TypeError: this.position is not a function**
    at Core.<anonymous> (cytoscape-undo-redo.js:234:1)
    at cytoscape.cjs.js:2922:1
    at forEachEventObj (cytoscape.cjs.js:2810:1)
    at Emitter.p.emit.p.trigger (cytoscape.cjs.js:2894:1)
    at Core.emit (cytoscape.cjs.js:11792:1)
    at cytoscape.cjs.js:2934:1
    at forEachEventObj (cytoscape.cjs.js:2814:1)
    at Emitter.p.emit.p.trigger (cytoscape.cjs.js:2894:1)
    at Element.emit (cytoscape.cjs.js:8868:1)
    at HTMLDivElement.mousedownHandler (cytoscape.cjs.js:19391:1)
（匿名） @ cytoscape-undo-redo.js:234
（匿名） @ cytoscape.cjs.js:2922
forEachEventObj @ cytoscape.cjs.js:2810
p.emit.p.trigger @ cytoscape.cjs.js:2894
emit @ cytoscape.cjs.js:11792
（匿名） @ cytoscape.cjs.js:2934
forEachEventObj @ cytoscape.cjs.js:2814
p.emit.p.trigger @ cytoscape.cjs.js:2894
emit @ cytoscape.cjs.js:8868
mousedownHandler @ cytoscape.cjs.js:19391
how can I solve it? please, thanks

**Comment by YUEchn** [comment]
I solve it, beacause I use the wrong cytoscape.js version, and the correctone is 3.3.0
